name: build-deploy-azure-app
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.0.0
      - name: Install dotnet
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore Nuget packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Publish
        run: dotnet publish github-actions-demo-app/github-actions-demo-app.csproj -c Release -o website
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: app
          path: website/**
          if-no-files-found: error
